#image: Visual Studio 2017 # this gives docker -> useless because it does not support Linux images.

environment:
  # In Appveyor we cant run RTL/GATE simulations because it does not support Linux-docker, or well only for $$$$$$
  PYHA_SKIP_RTL: "True"
  PYHA_SKIP_GATE: "True"
  matrix:
    - PYTHON: "C:\\Python36-x64"
#    - PYTHON: "C:\\Python37-x64"

install:
  - docker version
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest"


