# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.6

before_script:
    # INSTALL GHDL
#    - sudo bash -c 'echo deb http://ee.archive.ubuntu.com/ubuntu precise main universe > /etc/apt/sources.list.d/pyha_tmp.list'
#    - sudo apt-get update
#    - sudo apt-get install -y gnat-4.6-base, libgnat-4.6
#    - sudo rm -f /etc/apt/sources.list.d/pyha_tmp.list
    - sudo sh scripts/install_ghdl.sh
    - export PATH=$PATH:$PWD/ghdl/bin/

    # INSTALL COCOTB
    - sudo apt-get install git make gcc g++ swig python-dev
    - sh scripts/install_cocotb.sh #cant sudo this, files will lock, later
    - export PYHA_SKIP_QUARTUS_SIMS=1

install:
    - pip install .
    - pip install -r requirements_dev.txt

    - pip install coveralls
    - pip install codeclimate-test-reporter


script:
    - coverage run --source pyha -m py.test tests

after_success:
    - coveralls
    - codeclimate-test-reporter
