# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

before_script:
    # INSTALL GHDL
    - sh scripts/install_ghdl.sh
    - export PATH=$PATH:$PWD/ghdl/bin/

    # INSTALL COCOTB
    - sh scripts/install_cocotb.sh

install:
    - pip install .
    - pip install -r requirements_dev.txt
    - pip install coveralls
    - pip install codeclimate-test-reporter


script:
    - coverage run --source pyha -m py.test tests

after_success:
    - coveralls
    - codeclimate-test-reporter
