# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

before_script:
    # INSTALL GHDL
    - sudo apt-get -qq update
    - sudo apt-get install -y libgnat-4.6
    - wget https://github.com/tgingold/ghdl/releases/download/2016-09-14/ghdl-0.34dev-mcode-2016-09-14.tgz -O /tmp/ghdl.tar.gz
    - mkdir ghdl
    - tar -C ghdl -xvf /tmp/ghdl.tar.gz
    - export PATH=$PATH:$PWD/ghdl/bin/

    # INSTALL COCOTB
    - git clone https://github.com/potentialventures/cocotb

install:
#    - pip install -U tox
    - pip install .
    - pip install -r requirements_dev.txt
    - pip install coveralls


script:
    - coverage run --source pyha -m py.test tests
    - ghdl --version
    - cd cocotb/examples/adder/tests
    - make SIM=ghdl TOPLEVEL_LANG=vhdl

after_success:
    - coveralls


